package com.rameshta.magnetrail.core.generation

import com.rameshta.magnetrail.core.model.DifficultyBand

enum class GenerationProfile(
    val profileId: String,
    val difficultyBand: DifficultyBand,
    val minBoardSize: Int,
    val maxBoardSize: Int,
    val minArrows: Int,
    val maxArrows: Int,
    val minMagnets: Int,
    val maxMagnets: Int,
    val maxWalls: Int,
    val maxOpeningActions: Int,
    val minMagnetControlledActions: Int,
    val solverStateCap: Int,
    val maxAttempts: Int,
) {
    INTRO_EASY(
        profileId = "intro-easy-v1",
        difficultyBand = DifficultyBand.INTRO,
        minBoardSize = 4,
        maxBoardSize = 7,
        minArrows = 1,
        maxArrows = 3,
        minMagnets = 0,
        maxMagnets = 1,
        maxWalls = 3,
        maxOpeningActions = 3,
        minMagnetControlledActions = 0,
        solverStateCap = 2_000,
        maxAttempts = 64,
    ),
    DEVELOPING_MEDIUM(
        profileId = "developing-medium-v1",
        difficultyBand = DifficultyBand.DEVELOPING,
        minBoardSize = 5,
        maxBoardSize = 7,
        minArrows = 1,
        maxArrows = 5,
        minMagnets = 1,
        maxMagnets = 2,
        maxWalls = 5,
        maxOpeningActions = 4,
        minMagnetControlledActions = 1,
        solverStateCap = 8_000,
        maxAttempts = 96,
    ),
    ADVANCED_HARD(
        profileId = "advanced-hard-v1",
        difficultyBand = DifficultyBand.ADVANCED,
        minBoardSize = 5,
        maxBoardSize = 7,
        minArrows = 3,
        maxArrows = 7,
        minMagnets = 1,
        maxMagnets = 3,
        maxWalls = 8,
        maxOpeningActions = 7,
        minMagnetControlledActions = 1,
        solverStateCap = 20_000,
        maxAttempts = 128,
    ),
    DAILY_CHALLENGE(
        profileId = "daily-v1",
        difficultyBand = DifficultyBand.DEVELOPING,
        minBoardSize = 5,
        maxBoardSize = 6,
        minArrows = 3,
        maxArrows = 5,
        minMagnets = 1,
        maxMagnets = 2,
        maxWalls = 5,
        maxOpeningActions = 4,
        minMagnetControlledActions = 1,
        solverStateCap = 8_000,
        maxAttempts = 48,
    ),
}

const val GENERATOR_VERSION = 1
const val CONTENT_VERSION = 3
const val CERTIFICATION_SOLUTION_LIMIT = 32
