package com.rameshta.magnetrail.core.generation

import com.rameshta.magnetrail.core.model.DifficultyBand

enum class GenerationProfile(
    val profileId: String,
    val difficultyBand: DifficultyBand,
    val minBoardSize: Int,
    val maxBoardSize: Int,
    val minArrows: Int,
    val maxArrows: Int,
    val minMagnets: Int,
    val maxMagnets: Int,
    val maxWalls: Int,
    val maxOpeningActions: Int,
    val minMagnetControlledActions: Int,
    val solverStateCap: Int,
    val maxAttempts: Int,
    val minPolarityFlips: Int = 0,
    val minCriticalOrderConstraints: Int = 0,
    val minDifficultyScoreV2: Int = 0,
    val maxDifficultyScoreV2: Int = 100,
) {
    INTRO_EASY(
        profileId = "intro-easy-v1",
        difficultyBand = DifficultyBand.INTRO,
        minBoardSize = 4,
        maxBoardSize = 7,
        minArrows = 1,
        maxArrows = 3,
        minMagnets = 0,
        maxMagnets = 1,
        maxWalls = 3,
        maxOpeningActions = 3,
        minMagnetControlledActions = 0,
        solverStateCap = 2_000,
        maxAttempts = 64,
    ),
    DEVELOPING_MEDIUM(
        profileId = "developing-medium-v1",
        difficultyBand = DifficultyBand.DEVELOPING,
        minBoardSize = 5,
        maxBoardSize = 7,
        minArrows = 1,
        maxArrows = 5,
        minMagnets = 1,
        maxMagnets = 2,
        maxWalls = 5,
        maxOpeningActions = 4,
        minMagnetControlledActions = 1,
        solverStateCap = 8_000,
        maxAttempts = 96,
    ),
    ADVANCED_HARD(
        profileId = "advanced-hard-v1",
        difficultyBand = DifficultyBand.ADVANCED,
        minBoardSize = 5,
        maxBoardSize = 7,
        minArrows = 3,
        maxArrows = 7,
        minMagnets = 1,
        maxMagnets = 3,
        maxWalls = 8,
        maxOpeningActions = 7,
        minMagnetControlledActions = 1,
        solverStateCap = 20_000,
        maxAttempts = 128,
    ),
    DAILY_CHALLENGE(
        profileId = "daily-v1",
        difficultyBand = DifficultyBand.DEVELOPING,
        minBoardSize = 5,
        maxBoardSize = 6,
        minArrows = 3,
        maxArrows = 5,
        minMagnets = 1,
        maxMagnets = 2,
        maxWalls = 5,
        maxOpeningActions = 4,
        minMagnetControlledActions = 1,
        solverStateCap = 8_000,
        maxAttempts = 48,
    ),
    M52_ADVANCED_CONTINUATION(
        profileId = "m52-advanced-continuation-v1",
        difficultyBand = DifficultyBand.ADVANCED,
        minBoardSize = 6,
        maxBoardSize = 7,
        minArrows = 3,
        maxArrows = 7,
        minMagnets = 1,
        maxMagnets = 3,
        maxWalls = 7,
        maxOpeningActions = 7,
        minMagnetControlledActions = 1,
        solverStateCap = 30_000,
        maxAttempts = 192,
        minPolarityFlips = 1,
        minDifficultyScoreV2 = 31,
        maxDifficultyScoreV2 = 75,
    ),
    M52_MASTERY(
        profileId = "m52-mastery-v1",
        difficultyBand = DifficultyBand.ADVANCED,
        minBoardSize = 6,
        maxBoardSize = 7,
        minArrows = 5,
        maxArrows = 7,
        minMagnets = 2,
        maxMagnets = 3,
        maxWalls = 8,
        maxOpeningActions = 7,
        minMagnetControlledActions = 3,
        solverStateCap = 50_000,
        maxAttempts = 256,
        minPolarityFlips = 3,
        minDifficultyScoreV2 = 40,
        maxDifficultyScoreV2 = 90,
    ),
    PHASE0_INTRO_V3(
        profileId = "phase0-intro-v3",
        difficultyBand = DifficultyBand.INTRO,
        minBoardSize = 3,
        maxBoardSize = 4,
        minArrows = 1,
        maxArrows = 3,
        minMagnets = 0,
        maxMagnets = 1,
        maxWalls = 2,
        maxOpeningActions = 3,
        minMagnetControlledActions = 0,
        solverStateCap = 20_000,
        maxAttempts = 1,
    ),
    PHASE0_PLANNING_V3(
        profileId = "phase0-planning-v3",
        difficultyBand = DifficultyBand.DEVELOPING,
        minBoardSize = 3,
        maxBoardSize = 4,
        minArrows = 3,
        maxArrows = 5,
        minMagnets = 1,
        maxMagnets = 2,
        maxWalls = 3,
        maxOpeningActions = 5,
        minMagnetControlledActions = 1,
        solverStateCap = 50_000,
        maxAttempts = 1,
    ),
    PHASE0_ADVANCED_V3(
        profileId = "phase0-advanced-v3",
        difficultyBand = DifficultyBand.ADVANCED,
        minBoardSize = 4,
        maxBoardSize = 4,
        minArrows = 4,
        maxArrows = 7,
        minMagnets = 1,
        maxMagnets = 2,
        maxWalls = 3,
        maxOpeningActions = 7,
        minMagnetControlledActions = 1,
        solverStateCap = 100_000,
        maxAttempts = 1,
    ),
    PHASE1_ADVANCED_V3(
        profileId = "phase1-advanced-v3",
        difficultyBand = DifficultyBand.ADVANCED,
        minBoardSize = 6,
        maxBoardSize = 7,
        minArrows = 4,
        maxArrows = 7,
        minMagnets = 1,
        maxMagnets = 3,
        maxWalls = 8,
        maxOpeningActions = 7,
        minMagnetControlledActions = 1,
        solverStateCap = 100_000,
        maxAttempts = 160,
        minPolarityFlips = 1,
        minDifficultyScoreV2 = 25,
        maxDifficultyScoreV2 = 100,
    ),
}

const val GENERATOR_VERSION = 1
const val CONTENT_VERSION = 3
const val CERTIFICATION_SOLUTION_LIMIT = 32
const val M52_GENERATOR_VERSION = 2
const val M52_CONTENT_VERSION = 4
const val PHASE0_GENERATOR_VERSION = 3
const val PHASE0_CONTENT_VERSION = 5
const val PHASE1_GENERATOR_VERSION = 4
const val PHASE1_CONTENT_VERSION = 6
